### ISSUE TITLE
node not being installed properly in macos-latest

### ISSUE THREAD

**Issue by jakebeal** [ts-graphviz/setup-graphviz#578]
## Describe the bug

When our GitHub workflow for SBOL-utilities runs on macos-latest, ts-graphviz is used in its setup, and node crashes when it is run:

```
dyld[7183]: Library not loaded: '/usr/local/opt/icu4c/lib/libicui18n.73.dylib'
  Referenced from: '/usr/local/Cellar/node@18/18.1[9](https://github.com/SynBioDex/SBOL-utilities/actions/runs/8146488973/job/22265092207#step:6:10).1/bin/node'
  Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/usr/local/lib/libicui18n.73.dylib' (no such file), '/usr/lib/libicui18n.73.dylib' (no such file), '/usr/local/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/usr/local/lib/libicui18n.73.dylib' (no such file), '/usr/lib/libicui18n.73.dylib' (no such file)
/Users/runner/work/_temp/51aa4b5a-8fe6-464d-bc99-218fbb02bbbc.sh: line 1:  7183 Abort trap: 6           node --version
```

In the logs for ts-graphviz, I notice that both "node" and "node@18" are listed as being outdated formulae.
That makes me wonder whether brew isn't properly being updated in the script somehow?
Brew should be getting updated (I see the default value: `macos-skip-brew-update: false`), but I'm not sure that it's actually getting upgraded properly.

## To Reproduce

GitHub actions failure example: https://github.com/SynBioDex/SBOL-utilities/actions/runs/8146488973/job/22265092207

Success from two days previous: https://github.com/SynBioDex/SBOL-utilities/actions/runs/8126645318/job/22210629797

**Comment by jakebeal** [comment]
I've done a test that I think shows that brew upgrading is the key issue:

I added a step in our yaml workflow after setup-graphviz, which is: `brew upgrade node`

This then passed: https://github.com/SynBioDex/SBOL-utilities/actions/runs/8146910621/job/22266468946

**Comment by kamiazya** [comment]
@jakebeal

**Comment by kamiazya** [comment]
@jakebeal 
Thank you for reporting this issue and providing detailed information. Upon careful review, it appears that the problem described is related to the Node.js environment and its dependencies, and not directly to the setup-graphviz GitHub Action.

Our action is designed to install Graphviz via Homebrew and does not interact with the Node.js installation or its libraries.

To address the underlying issue with Node.js, particularly the error involving `libicui18n.73.dylib`, we suggest adding a step to your workflow that explicitly sets up Node.js using the [actions/setup-node GitHub Action](https://github.com/actions/setup-node). This approach will allow you to specify and fix the version of Node.js used in your workflow, potentially avoiding compatibility issues with the macOS environment and ensuring the necessary libraries are correctly linked.


Since the reported issue falls outside the scope of setup-graphviz, this ticket will be closed. However, we hope the suggestion above helps you address the Node.js related issue in your workflow. Should you encounter any further issues or have questions directly related to setup-graphviz, please do not hesitate to open a new issue.

Thank you for your understanding and cooperation.

**Comment by jakebeal** [comment]
@kamiazya unfortunately, your suggested fix does not seem to work.

Here are failures with both [Node 18](https://github.com/SynBioDex/SBOL-utilities/actions/runs/8336444712) and [Node 20](https://github.com/SynBioDex/SBOL-utilities/actions/runs/8335814101/job/22811948541). 

In these transcripts, note that the execution of setup-graphviz appears to ignore the copy of Node.js that is set up via setup-node, as brew installs its own `node` package (before ultimately failing). 

**The failure is now actually inside of setup-graphviz, rather than due to Node not being set up before, and does appear to be linked to the outdated packages used by setup-graphviz.**

**Comment by jakebeal** [comment]
Actually, can you point me to any copy of setup-graphviz that is currently actually working for a `macos-latest` image?

I forked another unrelated project where it had previously been working and found that this action is now failing for their macos-latest build: https://github.com/jakebeal/kagome/actions/runs/8337292144/job/22815789124

**Comment by pgleeson** [comment]
I'm also getting a possibly related error on macos-latest: https://github.com/ModECI/MDF/actions/runs/8347579020/job/22847503522. I've recently updated setup-graphviz version https://github.com/ModECI/MDF/commit/47a1dfe3913e034749a36a8fa02c46ce69dee586, but same error as before. Other OS versions working fine at this step.
Any fix for this would be greatly appreciated!
