### ISSUE TITLE
"sudo" unnecessary and actually not present on Ubuntu in GitHub Actions currently

### ISSUE THREAD

**Issue by mohawk2** [ts-graphviz/setup-graphviz#83]
Doing `sudo` on the `apt-get` commands did not work today, rather unexpectedly. It seems to work fine by omitting the `sudo`. See https://github.com/graphviz-perl/GraphViz2/runs/1348271077?check_suite_focus=true for the results, and apparently this is since Jun: https://github.com/nektos/act/issues/269

**Comment by kamiazya** [comment]
Thank you for the report.

I'll consider improvement methods while experimenting.

**Comment by mohawk2** [comment]
Unfortunately this is still failing: https://github.com/graphviz-perl/GraphViz2/runs/1358650761

**Comment by mohawk2** [comment]
Sorry for false report; the above was using `@v1` which obviously hasn't changed. Could you tag `@v2` or similar?

**Comment by kamiazya** [comment]
@mohawk2 
This issue has not been resolved yet and we are considering a solution.

I ran CI by specifying the release / v1 branch, but it failed.
I got a Permission Denied error because I don't have sudo.

https://github.com/kamiazya/setup-graphviz-example/runs/1350519652?check_suite_focus=true

---

In the CI execution log that was first reported, commands other than `sudo apt-get ...` are being executed, and I think it is necessary to identify the cause.

<img width="1920" alt="add_GitHub_actions_·_graphviz-perl_GraphViz2_2d044d4" src="https://user-images.githubusercontent.com/35218186/98269726-723a9580-1fd1-11eb-97be-e162a7f28db1.png">

And this was the same command running in `actions/checkout@v2`.

**Comment by mohawk2** [comment]
On further research, I think that `sudo` is needed when running on the main Ubuntu host, but is not needed or present when running in a container.

An immediate improvement that could be made would be to `console.error` any error that is caught before then trying to do `setFailed`. That might shed some extra light?

As for your point above, the `actions/checkout@v2` was working fine, so I'm not sure that is worth looking at further?

**Comment by mohawk2** [comment]
On further reflection: why not have a `with:` option of `sudo`, which defaults to `true`, and controls whether the commands are attempted with `sudo`? That seems to be a somewhat widely-used convention, as well.

**Comment by kamiazya** [comment]
Sorry for leaving it so long.

I made it possible to install with sudo on Linux.

**Comment by kamiazya** [comment]
@all-contributors please add @mohawk2  for bug, ideas
